POST http://localhost:5500/api/send-otp HTTP/1.1
Content-Type: application/json

{
    "phone": "9429653848"
}

###
POST http://localhost:5500/api/verify-otp HTTP/1.1
Content-Type: application/json

{
    "phone": "9429653848",
    "otp": 2024,
    "hash": "f7d12afa2b335606f7727dcaeb9cd7a668ea03f0016a4f3ac5216f93cae70fd4.1652262892761"
}
