version: "3"
services:
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend/
    container_name: backend
    restart: always
    ports:
      - "5500:5500"
    env_file:
      - ./backend/.env.dev
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    networks:
      - clubhouse
  frontend:
    build:
      dockerfile: dockerfile
      context: ./
    container_name: frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.dev
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - clubhouse
    depends_on:
      - backend
networks:
  clubhouse:
    driver: bridge
